//! # Machine
//!
//! This module represents a **3-Axis Computer Numerical Control** (CNC) machine.
//!
//! The machine runs on parsed [`Code`],
//! generated by the **G-Code [`Parser`](crate::parser::parser)** module.

use crate::parser::{Float, Int, parser::*};
use std::{
    fmt::{Debug, Display},
    ops::Neg,
};

/// Starting point of a machine with all axes at '0'.
pub const HOME_POS: Point = Point::new(0.0, 0.0, 0.0);

/// Represents *max* and *min* allowable values for a generic type `T`.
struct Limits<T> {
    max: T,
    min: T,
}

/// **Absolute** Maximum and Minimum values supported for [`Machine::max_travels`] for this module.
/// The fields of these [`Point`]s will be treated in [`Unit::default`] system.
///
/// Only **Z** axis will be forced to be negative.
/// Rest can be either positive or negative.
/// The reason of this restriction is that it is conventional to have **Z HOME_POS** above the
/// part, which requires that the machine can only travel in **negative Z** direction.
const TRAVEL_LIMITS: Limits<Point> = Limits {
    max: Point::new(1500.0, 1000.0, 1000.0),
    min: Point::new(150.0, 100.0, 100.0),
};

/// **Absolute** Maximum and Minimum ratios to maintain between axes lengths.
/// The order of specific axes is as follows:
/// - X : Y
/// - X : Z
/// - Y : Z
const RATIO_LIMITS: Limits<Point> = Limits {
    max: Point::new(2.0, 2.0, 1.5),
    min: Point::new(1.0, 1.0, 0.5),
};

/// Possible motion types to move the machine in.
/// Represents **Group 1** G-Codes.
#[derive(Copy, Clone, Default, Debug, PartialEq)]
pub enum Motion {
    #[default]
    Rapid,
    Feed,
    Arc(CircularDirection),
}

/// Possible ways to interpret given feed rate.
/// Represents **Group 5** G-Codes.
#[derive(Copy, Clone, Default, Debug, PartialEq)]
pub enum FeedMode {
    #[default]
    PerMinute,
    PerRev,
}

/// Possible levels to return to in a canned cycle.
#[derive(Copy, Clone, Default, Debug, PartialEq)]
pub enum ReturnLevel {
    #[default]
    Initial,
    Retract,
}

/// Possible unit standards for measurable values.
/// Represents **Group 6** G-Codes.
#[derive(Copy, Clone, Default, Debug, PartialEq)]
pub enum Unit {
    Imperial,
    #[default]
    Metric,
}

/// Possible planes for a 3-axis machine.
/// Represents **Group 2** G-Codes.
#[derive(Copy, Clone, Default, Debug, PartialEq)]
pub enum Plane {
    #[default]
    XY,
    XZ,
    YZ,
}

/// Possible ways to interpret axis commands.
/// Represents **Group 3** G-Codes.
#[derive(Default, Debug)]
pub enum Positioning {
    #[default]
    Absolute,
    Incremental,
}

/// Possible ways to turn the spindle.
#[derive(Copy, Clone, Default, Debug, PartialEq)]
pub enum CircularDirection {
    #[default]
    Clockwise,
    CounterClockwise,
}

#[derive(Debug, PartialEq)]
pub enum Direction {
    Left,
    Right,
    Up,
    Down,
}

/// Represents an offset `address` with a `direction`.
#[derive(Debug, PartialEq)]
pub struct Offset {
    address: Int,
    dir: Direction,
}

impl Offset {
    /// Generates a new [`Offset`] to be used with a `D` address.
    /// The `dir` provided must be [`Direction::Left`] or [`Direction::Right`] for diameter
    /// offsets.
    ///
    /// Returns [`MachineError::OffsetDirection`], if provided `dir` is invalid, indicating
    /// failure.
    pub fn build_d(address: Int, dir: Direction) -> Result<Self, MachineError> {
        if dir == Direction::Up || dir == Direction::Down {
            Err(MachineError::OffsetDirection(dir))
        } else {
            Ok(Self { address, dir })
        }
    }

    /// Generates a new [`Offset`] to be used with a `H` address.
    /// The `dir` provided must be [`Direction::Up`] or [`Direction::Down`] for height
    /// offsets.
    ///
    /// Returns [`MachineError::OffsetDirection`], if provided `dir` is invalid, indicating
    /// failure.
    pub fn build_h(address: Int, dir: Direction) -> Result<Self, MachineError> {
        if dir == Direction::Left || dir == Direction::Right {
            Err(MachineError::OffsetDirection(dir))
        } else {
            Ok(Self { address, dir })
        }
    }
}

/// Represents the current state of a [`Machine`](crate::machine).
#[derive(Debug)]
pub struct Machine {
    /// Interpret state values in the selected `units`.
    /// The Code the machine executes MAY OR MAY NOT be in the same units.
    /// All stored values must be in this unit standard.
    units: Unit,

    /// Interpret [`Code`]s in the selected `code_units`.
    code_units: Unit,

    /// **Positive extreme values** for each linear axis.
    /// The other extreme would naturally be `HOME_POS`.
    /// The values in this struct will be assumed to be in [`units`](Self::units).
    max_travels: Point,

    /// Workpiece offset, used to change relative zero point with `G54`.
    work_offset: Point,

    /// Current position of each axis.
    pos: Point,

    /// Current tool in the spindle.
    tool: Int,

    /// Optionally preload next tool, to be changed on *tool change (`M6`)* command.
    next_tool: Option<Int>,

    /// Commanded RPM for the spindle.
    speed: Option<Int>,
    spindle_on: bool,
    spindle_dir: CircularDirection,

    /// Active [`Motion`] type to use for moves.
    motion: Motion,

    /// Commanded cutting feed rate.
    feed: Option<Float>,

    /// Way in which to interpret the given feed value.
    feed_mode: FeedMode,

    coolant: bool,

    /// Plane to execute the [`Code`] on.
    plane: Plane,

    /// Interpret axis values absolutly or relatively.
    positioning: Positioning,

    /// Selected offset for tool diameter with a `D` code.
    d_offset: Option<Offset>,

    /// Selected offset for tool height with a `H` code.
    h_offset: Option<Offset>,

    /// Return level in canned cycles.
    return_level: ReturnLevel,
}

impl Machine {
    /// Constructs a new instance of [`Machine`] with all axes at [`HOME_POS`].
    ///
    /// Accepts a [`Point`], indicating positive extremes of the Machine to construct,
    /// and the measuring system [`Unit`] to use for machine moves.
    ///
    /// The *G-Code* that the machine executes need not be in the same [`Unit`]s.
    ///
    /// Returns a new `Machine` instance on success or [`MachineError`] on failure.
    ///
    /// # Errors:
    /// - [`MachineError::PositiveZ`] --
    ///   Z axis is detected to have a positive value.
    /// - [`MachineError::TravelsTooLong`] --
    ///   At least one axis is longer than what the constructor supports.
    /// - [`MachineError::TravelsTooShort`] --
    ///   At least one axis is shorter than what the constructor supports.
    /// - [`MachineError::WrongRatio`] --
    ///   At least two axes have weird values.
    pub fn build(max_travels: Point, units: Unit) -> Result<Self, MachineError> {
        let ratio = max_travels.ratio();

        if max_travels.z().is_sign_positive() {
            Err(MachineError::PositiveZ)
        } else if max_travels.over_abs(&TRAVEL_LIMITS.max) {
            Err(MachineError::TravelsTooLong)
        } else if max_travels.under_abs(&TRAVEL_LIMITS.min) {
            Err(MachineError::TravelsTooShort)
        } else if ratio.over_abs(&RATIO_LIMITS.max) || ratio.under_abs(&RATIO_LIMITS.min) {
            Err(MachineError::WrongRatio)
        } else {
            Ok(Machine {
                units,
                code_units: units,
                max_travels,
                work_offset: Point::default(),
                pos: Point::default(),
                tool: 0,
                next_tool: None,
                speed: None,
                spindle_on: false,
                spindle_dir: CircularDirection::default(),
                motion: Motion::default(),
                feed: None,
                feed_mode: FeedMode::default(),
                coolant: false,
                plane: Plane::default(),
                positioning: Positioning::default(),
                d_offset: None,
                h_offset: None,
                return_level: ReturnLevel::default(),
            })
        }
    }

    //
    // ########## PUBLIC GETTERS ##########
    //

    /// Return *maximum* travel for each axis of the [`Machine`].
    pub fn max_travels(&self) -> &Point {
        &self.max_travels
    }

    /// Returns `G54` work coordinate system.
    ///
    /// This offset is applied each time the machine has to move in absolute mode.
    pub fn work_offset(&self) -> &Point {
        &self.work_offset
    }

    /// Returns the current position of the machine.
    pub fn pos(&self) -> &Point {
        &self.pos
    }

    //
    // ########## PUBLIC SETTERS ##########
    //

    /// Interpret [`Code`] values in a new [`Unit`] standard.
    pub fn set_code_units(&mut self, code_units: Unit) {
        self.code_units = code_units;

        // change any existing feed rate to new units
        if let Some(feed) = self.feed {
            self.set_feed(feed);
        }
    }

    /// Set `G54` work coordinate system.
    ///
    /// **This is not verified to be inside the machine travels**.
    pub fn set_work_offset(&mut self, work_offset: Point) {
        self.work_offset = work_offset
    }

    /// Preload the *next tool* to use.
    pub fn set_next_tool(&mut self, next_tool: Int) {
        self.next_tool = Some(next_tool)
    }

    /// Set *spindle RPMs* to use.
    pub fn set_speed(&mut self, speed: Int) {
        self.speed = Some(speed)
    }

    /// Turn spindle off.
    pub fn spindle_off(&mut self) {
        self.spindle_on = false
    }

    /// Set *feedrate* to use.
    /// Peformes any unit conversion if necessary.
    pub fn set_feed(&mut self, mut feed: Float) {
        if self.units == Unit::Imperial && self.code_units == Unit::Metric {
            feed /= 25.4;
        } else if self.units == Unit::Metric && self.code_units == Unit::Imperial {
            feed *= 25.4;
        }

        self.feed = Some(feed)
    }

    /// Set `coolant` on or off.
    pub fn set_coolant(&mut self, coolant: bool) {
        self.coolant = coolant
    }

    /// Set active plane.
    pub fn set_plane(&mut self, plane: Plane) {
        self.plane = plane
    }

    /// Toggle between `absolute` or `relative` positioning.
    pub fn set_positioning(&mut self, positioning: Positioning) {
        self.positioning = positioning
    }

    /// Cancel any diameter offset, if active.
    pub fn cancel_dia_offset(&mut self) {
        self.d_offset = None
    }

    /// Cancel any height offset, if active.
    pub fn cancel_height_offset(&mut self) {
        self.h_offset = None
    }

    /// Toggle between motion types.
    pub fn set_motion(&mut self, motion: Motion) {
        self.motion = motion
    }

    /// Cancel any canned cycles.
    pub fn cancel_canned(&mut self) {}

    /// Toggle between `feed per minute` or `feed per rev` modes.
    pub fn set_feed_mode(&mut self, mode: FeedMode) {
        self.feed_mode = mode
    }

    /// Toggle between `inital` or `retract` return planes.
    pub fn set_return_level(&mut self, level: ReturnLevel) {
        self.return_level = level
    }

    //
    // ########## PUBLIC SETTERS, CAN FAIL ##########
    //

    /// Turn spindle on, if not already on.
    ///
    /// Accepts [`CircularDirection`] as *spindle direction* and optionally accepts
    /// new *spindle speed*, otherwise uses speed from previous blocks, if present.
    ///
    /// Returns [`MachineError::NoSpindleSpeed`] if no spindle speed was commanded before and
    /// `speed` provided is also `None`.
    pub fn spindle_on(
        &mut self,
        dir: CircularDirection,
        speed: Option<Int>,
    ) -> Result<(), MachineError> {
        self.speed = speed.or(self.speed);
        self.spindle_dir = dir;

        match self.speed {
            Some(_) => {
                self.spindle_on = true;
                Ok(())
            }
            None => Err(MachineError::NoSpindleSpeed),
        }
    }

    /// Changes current `tool` to:
    /// - `new_tool`, if the value is `Some`.
    /// - `next_tool`, if a tool was preloaded.
    ///
    /// `next_tool` will be always be set to `None` after the tool change.
    ///
    /// Returns [`MachineError::NoTool`] if no `next_tool` was commanded before and
    /// `new_tool` provided is also `None`.
    pub fn tool_change(&mut self, new_tool: Option<Int>) -> Result<(), MachineError> {
        self.next_tool = new_tool.or(self.next_tool);

        match self.next_tool {
            Some(t) => {
                self.tool = t;
                self.next_tool = None;
                Ok(())
            }
            None => Err(MachineError::NoTool),
        }
    }

    /// Sets a `Some` value for `d_offset`.
    /// The `dir` provided must be [`Direction::Left`] or [`Direction::Right`] for diameter
    /// offsets.
    ///
    /// Returns [`MachineError::OffsetDirection`], if provided `dir` is invalid, indicating
    /// failure.
    pub fn set_dia_offset(&mut self, address: Int, dir: Direction) -> Result<(), MachineError> {
        self.d_offset = Some(Offset::build_d(address, dir)?);
        Ok(())
    }

    /// Sets a `Some` value for `h_offset`.
    /// The `dir` provided must be [`Direction::Up`] or [`Direction::Down`] for height
    /// offsets.
    ///
    /// Returns [`MachineError::OffsetDirection`], if provided `dir` is invalid, indicating
    /// failure.
    pub fn set_height_offset(&mut self, address: Int, dir: Direction) -> Result<(), MachineError> {
        self.h_offset = Some(Offset::build_h(address, dir)?);
        Ok(())
    }

    //
    // ########## PUBLIC INTERPOLATION METHODS ##########
    //

    /// Moves machine after checking for [`Positioning`] setting of the machine in **Rapid** rate.
    ///
    /// Respects the current unit selections for both [`Machine`] and [`Code`],
    /// and any unit conversions are performed as necessary.
    ///
    /// Returns [`MachineError`] on failure.
    ///
    /// # Errors:
    /// - [`MachineError::Overtravel`] -- Atleast one axis exceeds `max_travels` or `HOME_POS`.
    pub fn rapid_move(&mut self, pos: PartialPoint) -> Result<(), MachineError> {
        self.set_motion(Motion::Rapid);
        self.move_machine(pos)
    }

    /// Moves machine after checking for [`Positioning`] setting of the machine in **Feed** rate.
    ///
    /// Respects the current unit selections for both [`Machine`] and [`Code`],
    /// and any unit conversions (including for **feedrate**) are performed as necessary.
    ///
    /// Returns [`MachineError`] on failure.
    ///
    /// # Errors:
    /// - [`MachineError::Overtravel`] -- Atleast one axis exceeds `max_travels` or `HOME_POS`.
    /// - [`MachineError::NoFeed`] -- No feed was commanded in previous blocks and is found `None`.
    pub fn feed_move(
        &mut self,
        pos: PartialPoint,
        feed: Option<Float>,
    ) -> Result<(), MachineError> {
        self.set_motion(Motion::Feed);

        if let Some(f) = feed {
            self.set_feed(f); // takes care of any unit conversion
        }

        match self.feed {
            Some(_) => {
                // move only when feed is detected.
                self.move_machine(pos)
            }
            None => Err(MachineError::NoFeed),
        }
    }

    /// Moves machine in a **circular path**,
    /// after checking for [`Positioning`] setting of the machine in **Feed** rate.
    ///
    /// Respects the current unit selections for both [`Machine`] and [`Code`],
    /// and any unit conversions (including for **feedrate**) are performed as necessary.
    ///
    /// Returns [`MachineError`] on failure.
    ///
    /// # Errors:
    /// - [`MachineError::Overtravel`] -- Atleast one axis exceeds `max_travels` or `HOME_POS`.
    /// - [`MachineError::NoFeed`] -- No feed was commanded in previous blocks and is found `None`.
    pub fn arc_move(
        &mut self,
        pos: PartialPoint,
        method: CircleMethod,
        dir: CircularDirection,
        feed: Option<Float>,
    ) -> Result<(PlanarPoint, Float), MachineError> {
        self.set_motion(Motion::Arc(dir));

        if let Some(f) = feed {
            self.set_feed(f);
        }

        if self.feed.is_none() {
            return Err(MachineError::NoFeed);
        }

        let start_pos = self.pos();
        // retain None variants as start_pos
        let end_pos = self.new_pos(pos);

        let (start_pos_planar, end_pos_planar) = match self.plane {
            Plane::XY => (
                PlanarPoint::new(self.plane, start_pos.x(), start_pos.y()),
                PlanarPoint::new(self.plane, end_pos.x(), end_pos.y()),
            ),
            Plane::XZ => (
                PlanarPoint::new(self.plane, start_pos.x(), start_pos.z()),
                PlanarPoint::new(self.plane, end_pos.x(), end_pos.z()),
            ),
            Plane::YZ => (
                PlanarPoint::new(self.plane, start_pos.y(), start_pos.z()),
                PlanarPoint::new(self.plane, end_pos.y(), end_pos.z()),
            ),
        };

        // convert `method` units
        let method = match method {
            CircleMethod::RelativePoint(mut rel_center) => {
                self.to_machine_units_partial(&mut rel_center);
                CircleMethod::RelativePoint(rel_center)
            }
            CircleMethod::FixedRadius(mut rad) => {
                if self.units == Unit::Imperial && self.code_units == Unit::Metric {
                    rad /= 25.4;
                } else if self.units == Unit::Metric && self.code_units == Unit::Imperial {
                    rad *= 25.4;
                };

                CircleMethod::FixedRadius(rad)
            }
        };

        let (center, radius) = arc_info(&start_pos_planar, &end_pos_planar, method, dir)?;

        // TODO verify if the arc overtravels anywhere between the points

        // now we know the circle is possible
        // and end_pos is already in machine units
        self.set_pos(end_pos)?;

        Ok((center, radius))
    }

    /// Moves `Some` variants of `pos` to the value inside.
    ///
    /// This function differs from [`move_machine`](Self::move_machine) in the way that,
    /// it does not consider any `work_offset` & `positioning` setting of the [`Machine`] and just
    /// moves the machine axes to desired location.
    ///
    /// Returns [`MachineError::Overtravel`] if any axis exceeds `max_travels` or `HOME_POS`,
    /// indicating failure.
    ///
    /// This function also respects the current unit selections for both [`Machine`] and [`Code`],
    /// and any unit conversions are performed as necessary.
    pub fn move_machine_pos(&mut self, mut pos: PartialPoint) -> Result<(), MachineError> {
        self.to_machine_units_partial(&mut pos);

        let new_pos = Point::new(
            pos.x().unwrap_or(self.pos().x()),
            pos.y().unwrap_or(self.pos().y()),
            pos.z().unwrap_or(self.pos().z()),
        );

        self.set_pos(new_pos)
    }

    //
    // ########## INTERPOLATION HELPER METHODS ##########
    //

    /// Moves machine using [`rate`](Machine::rate),
    /// after checking for [`Positioning`] setting of the machine.
    ///
    /// Returns [`MachineError::Overtravel`] if any axis exceeds `max_travels` or `HOME_POS`,
    /// indicating failure.
    ///
    /// Respects the current unit selections for both [`Machine`] and [`Code`],
    /// and any unit conversions are performed as necessary.
    pub fn move_machine(&mut self, pos: PartialPoint) -> Result<(), MachineError> {
        let new_pos = self.new_pos(pos);
        self.set_pos(new_pos)
    }

    /// Calculates the new position for each axis,
    /// after checking for [`Positioning`] setting of the [`Machine`].
    ///
    /// Applies `work_offset` if present, for [`Positioning::Absolute`]
    /// and respects the current unit selections for both [`Machine`] and [`Code`],
    /// and any unit conversions are performed as necessary.
    ///
    /// Returns a new [`Point`] with each axis filled.
    fn new_pos(&self, mut pos: PartialPoint) -> Point {
        self.to_machine_units_partial(&mut pos);

        match self.positioning {
            Positioning::Absolute => Point::new(
                pos.x()
                    .map_or(self.pos().x(), |x| self.work_offset().x() + x),
                pos.y()
                    .map_or(self.pos().y(), |y| self.work_offset().y() + y),
                pos.z()
                    .map_or(self.pos().z(), |z| self.work_offset().z() + z),
            ),
            Positioning::Incremental => Point::new(
                self.pos().x() + pos.x().unwrap_or(0.0),
                self.pos().y() + pos.y().unwrap_or(0.0),
                self.pos().z() + pos.z().unwrap_or(0.0),
            ),
        }
    }

    /// Set the current machine position for all axes.
    /// Does **NO UNIT CONVERSION**, even if the *machine* and *code* units differ.
    ///
    /// Returns [`MachineError::Overtravel`] if any axis exceeds `max_travels` or `HOME_POS`,
    /// indicating failure.
    fn set_pos(&mut self, pos: Point) -> Result<(), MachineError> {
        self.check_overtravel(&pos)?;
        self.pos = pos;
        Ok(())
    }

    //
    // ########## OTHER HELPER METHODS ##########
    //

    /// Accepts a *mutable reference to [`Point`]* in `code_units`.
    /// Converts the units of all fields to Machine units.
    fn to_machine_units(&self, point: &mut Point) {
        if self.units == Unit::Imperial && self.code_units == Unit::Metric {
            point.to_imperial()
        } else if self.units == Unit::Metric && self.code_units == Unit::Imperial {
            point.to_metric()
        }
    }

    /// Accepts a *mutable reference to [`Point`]* in `code_units`.
    /// Converts the units of all `Some` variant fields to Machine units.
    /// `None` variants are not changed.
    fn to_machine_units_partial(&self, point: &mut PartialPoint) {
        if self.units == Unit::Imperial && self.code_units == Unit::Metric {
            point.to_imperial()
        } else if self.units == Unit::Metric && self.code_units == Unit::Imperial {
            point.to_metric()
        }
    }

    /// Checks if the given [`Point`] lies with `machine_travels` or not.
    /// Returns [`MachineError::Overtravel`] the point is outside of `machine_travels`.
    fn check_overtravel(&self, point: &Point) -> Result<(), MachineError> {
        match self.max_travels.x().is_sign_positive() {
            true => {
                if !(HOME_POS.x()..=self.max_travels.x()).contains(&point.x()) {
                    return Err(MachineError::Overtravel(b'X', point.x()));
                }
            }

            false => {
                if !(self.max_travels.x()..=HOME_POS.x()).contains(&point.x()) {
                    return Err(MachineError::Overtravel(b'X', point.x()));
                }
            }
        };

        match self.max_travels.y().is_sign_positive() {
            true => {
                if !(HOME_POS.y()..=self.max_travels.y()).contains(&point.y()) {
                    return Err(MachineError::Overtravel(b'Y', point.y()));
                }
            }

            false => {
                if !(self.max_travels.y()..=HOME_POS.y()).contains(&point.y()) {
                    return Err(MachineError::Overtravel(b'Y', point.y()));
                }
            }
        };

        match self.max_travels.z().is_sign_positive() {
            true => panic!("Positive passed Machine construction. Logic Error!"),

            false => {
                if !(self.max_travels.z()..=HOME_POS.z()).contains(&point.z()) {
                    return Err(MachineError::Overtravel(b'Z', point.z()));
                }
            }
        };

        Ok(())
    }
}

/// A *tuple struct* that represents a **2D Point** on a specific **Plane**.
#[derive(Debug, PartialEq)]
pub struct PlanarPoint(Plane, Float, Float);

impl PlanarPoint {
    /// Constructor for a [`PlanarPoint`].
    ///
    /// For a given [`Plane`], *first* represents the value for first axis letter and *second*
    /// represents the second axis letter.
    /// For example:
    /// ```
    /// PlanarPoint::new(Plane::XY, 1.0, 2.0); // Constructs point with X = 1.0 & Y = 2.0.
    /// PlanarPoint::new(Plane::XZ, 3.0, 4.0); // Constructs point with X = 3.0 & Z = 4.0.
    /// PlanarPoint::new(Plane::YZ, 5.0, 6.0); // Constructs point with Y = 5.0 & Z = 6.0.
    /// ```
    pub fn new(plane: Plane, first: Float, second: Float) -> Self {
        Self(plane, first, second)
    }

    /// Returns selected plane for the point.
    pub fn plane(&self) -> Plane {
        self.0
    }

    /// Returns the first axis value for the selected plane.
    pub fn first(&self) -> Float {
        self.1
    }

    /// Returns the second axis value for the selected plane.
    pub fn second(&self) -> Float {
        self.2
    }

    /// Calculates distance between two [`PlanarPoint`]s.
    ///
    /// Both the points must lie on the **same plane**, otherwise [`MachineError::PointsOffPlane`]
    /// is returned.
    pub fn dist(&self, other: &Self) -> Result<Float, MachineError> {
        if self.plane() == other.plane() {
            Ok(
                ((self.first() - other.first()).powi(2) + (self.second() - other.second()).powi(2))
                    .sqrt(),
            )
        } else {
            Err(MachineError::PointsOffPlane)
        }
    }
}

/// Validate if an *arc* is possible between two points and return its properties.
/// This function takes care of all the geometric Math for circular interpolation paths.
///
/// Accepts:
/// - Start and end points of the arc as [`PlanarPoint`]s, which must lie on the same plane.
/// - [`CircleMethod`] to use for calculating the radius of possible arc(s).
/// - [`CircularDirection`] for selecting a particular center point, in case more than one circles
///   are possible.
///
/// On success, returns a *tuple* consisting of two fields:
/// - The *center [`PlanarPoint`]* of the circle that satisfies the given conditions.
/// - The *radius* of the said circle
///
/// On failure, returns [`MachineError`].
///
/// # Reference: [`Math Stack Exchange`](https://math.stackexchange.com/questions/1781438/finding-the-center-of-a-circle-given-two-points-and-a-radius-algebraically)
///
/// # Errors:
/// - [`MachineError::PointsOffPlane`] -- Both points do not lie on the requested plane.
/// - [`MachineError::PointsIntersect`] -- Both provided points have the same coordinates.
/// - [`MachineError::CenterOffPlane`] -- The relative center provided does not lie on the
///   requested plane.
/// - [`MachineError::InvalidCircle`] -- The provided or calculated radius does not satisfy both
///   the points.
fn arc_info(
    current_pos: &PlanarPoint,
    new_pos: &PlanarPoint,
    method: CircleMethod,
    dir: CircularDirection,
) -> Result<(PlanarPoint, Float), MachineError> {
    // plane to create the circle on
    let plane = current_pos.plane();

    if new_pos.plane() != plane {
        return Err(MachineError::PointsOffPlane);
    }

    if current_pos == new_pos {
        return Err(MachineError::PointsIntersect);
    }

    match method {
        CircleMethod::RelativePoint(ref rel_center) => {
            // all fields cannot be None or Some.
            if rel_center.is_none() || rel_center.is_some() {
                panic!("Invalid Relative Center passed parser validation. Logic Error!");
            }

            // absolute center on the same plane as both the points
            let center = match plane {
                Plane::XY if rel_center.z().is_some() => return Err(MachineError::CenterOffPlane),

                Plane::XZ if rel_center.y().is_some() => return Err(MachineError::CenterOffPlane),

                Plane::YZ if rel_center.x().is_some() => return Err(MachineError::CenterOffPlane),

                Plane::XY => PlanarPoint::new(
                    plane,
                    rel_center
                        .x()
                        .map_or(current_pos.first(), |x| current_pos.first() + x),
                    rel_center
                        .y()
                        .map_or(current_pos.second(), |y| current_pos.second() + y),
                ),

                Plane::XZ => PlanarPoint::new(
                    plane,
                    rel_center
                        .x()
                        .map_or(current_pos.first(), |x| current_pos.first() + x),
                    rel_center
                        .z()
                        .map_or(current_pos.second(), |z| current_pos.second() + z),
                ),

                Plane::YZ => PlanarPoint::new(
                    plane,
                    rel_center
                        .y()
                        .map_or(current_pos.first(), |y| current_pos.first() + y),
                    rel_center
                        .z()
                        .map_or(current_pos.second(), |z| current_pos.second() + z),
                ),
            };

            let radius = current_pos.dist(&center)?;

            // in this method the distance between the points cannot be greater than the diameter

            // new point not at the same distance.
            if (new_pos.dist(&center)? - radius).abs() > 1e-10 {
                Err(MachineError::InvalidCircle(method))
            } else {
                Ok((center, radius))
            }
        }

        CircleMethod::FixedRadius(radius) => {
            assert!(
                radius.abs() > 1e-10,
                "Invalid radius passed parser validation. Logic Error!."
            );

            // if radius is negative, make it positive and make the function choose the major arc
            // otherwise choose minor arc on positive R value
            let (radius, minor) = if radius.signum() == 1.0 {
                (radius, true)
            } else if radius.signum() == -1.0 {
                (radius.neg(), false)
            } else {
                panic!("Provided number is Not a Number (NaN).");
            };

            let dist = current_pos.dist(new_pos)?;

            // distance more than diameter
            if dist > 2.0 * radius.abs() {
                return Err(MachineError::InvalidCircle(method));
            }

            let midpoint = PlanarPoint::new(
                plane,
                current_pos.first().midpoint(new_pos.first()),
                current_pos.second().midpoint(new_pos.second()),
            );

            // how much is the midpoint off from the current position.
            // plane is irrelevant in this var.
            let delta = PlanarPoint::new(
                plane,
                midpoint.first() - current_pos.first(),
                midpoint.second() - current_pos.second(),
            );

            // points are on the diameter
            if (2.0 * radius - dist).abs() < 1e-10 {
                return Ok((midpoint, radius));
            }

            // make dist as distance to midpoint only
            let dist = dist / 2.0;

            // length of line joining midpoint and center, the perpendicular bisector
            let bisector = (radius.powi(2) - dist.powi(2)).sqrt();

            // TODO create diagram to prove the result for all 4 quadrants
            let center = match (minor, dir) {
                (true, CircularDirection::Clockwise)
                | (false, CircularDirection::CounterClockwise) => PlanarPoint::new(
                    plane,
                    midpoint.first() + (bisector * delta.second()) / dist,
                    midpoint.second() - (bisector * delta.first()) / dist,
                ),

                (true, CircularDirection::CounterClockwise)
                | (false, CircularDirection::Clockwise) => PlanarPoint::new(
                    plane,
                    midpoint.first() - (bisector * delta.second()) / dist,
                    midpoint.second() + (bisector * delta.first()) / dist,
                ),
            };

            Ok((center, radius))
        }
    }
}

/// Possible errors that can happen during machine construction and interpolation.
#[derive(Debug, PartialEq)]
pub enum MachineError {
    /// Positive value detected in `max_travels` for Z axis during machine construction.
    PositiveZ,
    TravelsTooLong,
    TravelsTooShort,
    /// The resulting machine would be an odd shape.
    WrongRatio,
    Overtravel(u8, Float),
    /// Spindle On was commanded, but no spindle speed was provided.
    NoSpindleSpeed,
    /// Tool change was commanded, but no tool number was provided.
    NoTool,
    /// Feed move was commanded, but no feed was provided.
    NoFeed,
    /// Points of the requested circle do not lie on the same plane.
    PointsOffPlane,
    /// Both provided circle points are the same.
    PointsIntersect,
    /// Circle not possible due to method specific method requirements.
    InvalidCircle(CircleMethod),
    /// Provided center point does not lie on the selected plane.
    CenterOffPlane,
    /// Provided direction does not match with offset type.
    OffsetDirection(Direction),
}

impl Display for MachineError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        write!(
            f,
            "{}",
            match self {
                Self::PositiveZ => format!(
                    "Z Axis travels cannot be positive.\nPlease provide a valid negative value between: -{:?} and -{:?}", TRAVEL_LIMITS.max.z(), TRAVEL_LIMITS.min.z()
                ),
                Self::TravelsTooLong => format!(
                    "Cannot construct a 'Machine' this long.\nPlease provide values less than:\nX: {:?}\nY: {:?}\nZ: -{:?}", TRAVEL_LIMITS.max.x(), TRAVEL_LIMITS.max.y(), TRAVEL_LIMITS.max.z()
                ),
                Self::TravelsTooShort => format!(
                    "Cannot construct a 'Machine' this short.\nPlease provide values larger than:\nX: {:?}\nY: {:?}\nZ: -{:?}", TRAVEL_LIMITS.min.x(), TRAVEL_LIMITS.min.y(), TRAVEL_LIMITS.min.z()
                ),
                Self::WrongRatio =>
                    "The resultant machine would have a particular axis too long or too short.\nPlease reconsider axis lengths.".to_string(),
                Self::Overtravel(axis, coord) => format!(
                    "Overtravel:\n'{axis}' of the machine overtravels because of the last move to {coord}."
                ),
                Self::NoSpindleSpeed =>
                    "No Spindle Speed Commanded:\nA spindle action was commanded, but no 'S' was detected throughout the program.".to_string(),
                Self::NoTool =>
                    "No Tool Commanded:\nA tool change was commanded, but no 'T' was detected on the same block and no tool was preloaded.".to_string(),
                Self::NoFeed =>
                    "No Feed Commanded:\nA feed move was commanded, but no 'F' was detected throughout the program.".to_string(),
                Self::PointsOffPlane =>
                    "Points are not detected to be on the same plane:\nBoth the points must be on the same plane to be considered valid.".to_string(),
                Self::PointsIntersect =>
                    "Ambiguous Circle Detected:\nThe start and end points of the requested circle are same and therefore the circle cannot be constructed.".to_string(),
                Self::InvalidCircle(method) => match method {
                    CircleMethod::RelativePoint(_) =>
                        "Invalid Circle Requested:\nThe start and end points of the requested circle are not found to be at the same distance from the specified center, which is invalid.".to_string(),
                    CircleMethod::FixedRadius(_) =>
                        "Invalid Circle Requested:\nThe distance between the start and end points is found to be more than the diameter provided, which is invalid.".to_string(),
                },
                Self::CenterOffPlane =>
                    "Invalid Relative Center Point Detected:\nThe relative center provided does not lie only on the selected plane, which is invalid.".to_string(),
                Self::OffsetDirection(dir) => match dir {
                    Direction::Up | Direction::Down => format!(
                        "Invalid Offset Direction Detected:\nThe following direction was detected for a Diameter offset, which is invalid: {dir:?}."
                    ),
                    Direction::Left | Direction::Right => format!(
                        "Invalid Offset Direction Detected:\nThe following direction was detected for a Height offset, which is invalid: {dir:?}."
                    ),
                },
            }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn construct_positive_z() {
        assert_eq!(
            Machine::build(Point::new(150.0, 500.0, 500.0), Unit::default()).unwrap_err(),
            MachineError::PositiveZ
        );
    }

    #[test]
    fn construct_long_travels() {
        assert_eq!(
            Machine::build(Point::new(2000.0, 1000.0, -500.0), Unit::default()).unwrap_err(),
            MachineError::TravelsTooLong
        );
    }

    #[test]
    fn construct_short_travels() {
        assert_eq!(
            Machine::build(Point::new(100.0, 75.0, -75.0), Unit::default()).unwrap_err(),
            MachineError::TravelsTooShort
        );
    }

    #[test]
    fn construct_wrong_ratio() {
        assert_eq!(
            Machine::build(Point::new(1500.0, 100.0, -100.0), Unit::default()).unwrap_err(),
            MachineError::WrongRatio
        );
    }

    #[test]
    // Must pass
    fn construct_good() {
        assert!(Machine::build(Point::new(-1000.0, 750.0, -500.0), Unit::default()).is_ok());
    }

    // Test Machine methods

    #[test]
    fn overtravel_set() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::default()).unwrap();

        assert_eq!(
            m.set_pos(Point::new(-100.0, 500.0, -300.0)).unwrap_err(),
            MachineError::Overtravel(b'X', -100.0)
        );

        assert_eq!(
            m.set_pos(Point::new(1200.0, 500.0, -300.0)).unwrap_err(),
            MachineError::Overtravel(b'X', 1200.0)
        );
    }

    #[test]
    fn unit_standards() {
        // machine metric and code metric
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Metric).unwrap();
        m.set_code_units(Unit::Metric);
        m.move_machine(PartialPoint::new(Some(25.4), Some(25.4), Some(-25.4)))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(25.4, 25.4, -25.4));

        // machine imperial and code imperial
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Imperial).unwrap();
        m.set_code_units(Unit::Imperial);
        m.move_machine(PartialPoint::new(Some(1.0), Some(1.0), Some(-1.0)))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(1.0, 1.0, -1.0));

        // machine imperial and code metric
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Imperial).unwrap();
        m.set_code_units(Unit::Metric);
        m.move_machine(PartialPoint::new(Some(25.4), Some(25.4), Some(-25.4)))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(1.0, 1.0, -1.0));

        // machine metric and code imperial
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Metric).unwrap();
        m.set_code_units(Unit::Imperial);
        m.move_machine(PartialPoint::new(Some(1.0), Some(1.0), Some(-1.0)))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(25.4, 25.4, -25.4));
    }

    #[test]
    fn absolute_move() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Metric).unwrap();
        m.set_positioning(Positioning::Absolute);

        // with no g54 offset
        m.move_machine(PartialPoint::new(Some(100.0), None, None))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(100.0, 0.0, 0.0));

        // with g54 offset
        m.set_work_offset(Point::new(100.0, 100.0, -100.0));
        m.move_machine(PartialPoint::new(Some(100.0), Some(0.0), None))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(200.0, 100.0, 0.0));

        // overtravel
        assert_eq!(
            m.move_machine(PartialPoint::new(Some(901.0), Some(0.0), None))
                .unwrap_err(),
            MachineError::Overtravel(b'X', 1001.0)
        ); // tries to move X to 1001.0
    }

    #[test]
    fn incremental_move() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Imperial).unwrap();
        m.set_positioning(Positioning::Incremental);

        // with no g54 offset
        m.move_machine(PartialPoint::new(Some(100.0), None, None))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(100.0, 0.0, 0.0));

        // with g54 offset
        m.set_work_offset(Point::new(100.0, 100.0, -100.0)); // has no effect
        m.move_machine(PartialPoint::new(Some(200.0), Some(0.0), None))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(300.0, 0.0, 0.0));

        // overtravel
        assert_eq!(
            m.move_machine(PartialPoint::new(Some(100.0), Some(751.0), None))
                .unwrap_err(),
            MachineError::Overtravel(b'Y', 751.0)
        ); // tries to move Y to 751.0
    }

    #[test]
    fn machine_move() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Imperial).unwrap();

        // with no g54 offset
        m.move_machine_pos(PartialPoint::new(Some(100.0), None, Some(-500.0)))
            .unwrap();
        assert_eq!(m.pos(), &Point::new(100.0, 0.0, -500.0));

        // with g54 offset
        m.set_work_offset(Point::new(100.0, 100.0, -100.0));
        m.move_machine_pos(PartialPoint::new(Some(200.0), Some(100.0), None))
            .unwrap(); // Z will be saved from previous move
        assert_eq!(m.pos(), &Point::new(200.0, 100.0, -500.0));

        // overtravel
        assert_eq!(
            m.move_machine_pos(PartialPoint::new(Some(0.0), Some(0.0), Some(1.0)))
                .unwrap_err(),
            MachineError::Overtravel(b'Z', 1.0)
        ); // tries to move Z to 1.0
    }

    #[test]
    fn spindle() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Imperial).unwrap();

        assert_eq!(
            m.spindle_on(CircularDirection::default(), None)
                .unwrap_err(),
            MachineError::NoSpindleSpeed
        );

        // no speed required when preset before
        m.set_speed(1000);
        assert!(m.spindle_on(CircularDirection::default(), None).is_ok());
        assert_eq!(m.speed, Some(1000));

        // providing new speed overwrites previous speed
        assert!(
            m.spindle_on(CircularDirection::default(), Some(500))
                .is_ok()
        );
        assert_eq!(m.speed, Some(500));
    }

    #[test]
    fn tool() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::Imperial).unwrap();

        assert_eq!(m.tool_change(None).unwrap_err(), MachineError::NoTool);

        // no tool required when preset before
        m.set_next_tool(1);
        assert!(m.tool_change(None).is_ok());
        assert_eq!(m.tool, 1);
        assert_eq!(m.next_tool, None); // next tool should always be reset

        // providing new tool overwrites any preloaded tool
        m.set_next_tool(5);
        assert!(m.tool_change(Some(10)).is_ok());
        assert_eq!(m.tool, 10);
        assert_eq!(m.next_tool, None);
    }

    // test to retrieve circle properties.
    #[test]
    fn test_arc_info() {
        // rel center
        let start = PlanarPoint::new(Plane::XY, -3.0, 4.0);
        let end = PlanarPoint::new(Plane::XY, 3.0, 4.0);

        let method = CircleMethod::RelativePoint(PartialPoint::new(Some(3.0), Some(-4.0), None));
        let (center, radius) =
            arc_info(&start, &end, method.clone(), CircularDirection::Clockwise).unwrap();

        assert_eq!(radius, 5.0);
        assert_eq!(center.first(), 0.0);
        assert_eq!(center.second(), 0.0);

        let method = CircleMethod::RelativePoint(PartialPoint::new(Some(3.0), Some(4.0), None));
        let (center, radius) =
            arc_info(&start, &end, method.clone(), CircularDirection::Clockwise).unwrap();

        assert_eq!(radius, 5.0);
        assert_eq!(center.first(), 0.0);
        assert_eq!(center.second(), 8.0);

        // positive radius should get minor arc
        let method = CircleMethod::FixedRadius(5.0);
        let (center, radius) =
            arc_info(&start, &end, method.clone(), CircularDirection::Clockwise).unwrap();

        assert_eq!(radius, 5.0);
        assert_eq!(center.first(), 0.0);
        assert_eq!(center.second(), 0.0);

        let (center, radius) = arc_info(
            &start,
            &end,
            method.clone(),
            CircularDirection::CounterClockwise,
        )
        .unwrap();

        assert_eq!(radius, 5.0);
        assert_eq!(center.first(), 0.0);
        assert_eq!(center.second(), 8.0);

        // negative radius should get major arc
        let method = CircleMethod::FixedRadius(-5.0);
        let (center, radius) =
            arc_info(&start, &end, method.clone(), CircularDirection::Clockwise).unwrap();

        assert_eq!(radius, 5.0);
        assert_eq!(center.first(), 0.0);
        assert_eq!(center.second(), 8.0);

        let (center, radius) =
            arc_info(&start, &end, method, CircularDirection::CounterClockwise).unwrap();

        assert_eq!(radius, 5.0);
        assert_eq!(center.first(), 0.0);
        assert_eq!(center.second(), 0.0);
    }

    #[test]
    fn offset_set() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, -500.0), Unit::default()).unwrap();

        assert_eq!(
            m.set_dia_offset(2, Direction::Up).unwrap_err(),
            MachineError::OffsetDirection(Direction::Up)
        );
        assert_eq!(
            m.set_dia_offset(3, Direction::Down).unwrap_err(),
            MachineError::OffsetDirection(Direction::Down)
        );
        m.set_dia_offset(3, Direction::Left).unwrap();
        assert_eq!(
            m.d_offset,
            Some(Offset {
                address: 3,
                dir: Direction::Left
            })
        );
        m.cancel_dia_offset();
        assert_eq!(m.d_offset, None);

        assert_eq!(
            m.set_height_offset(2, Direction::Left).unwrap_err(),
            MachineError::OffsetDirection(Direction::Left)
        );
        assert_eq!(
            m.set_height_offset(3, Direction::Right).unwrap_err(),
            MachineError::OffsetDirection(Direction::Right)
        );
        m.set_height_offset(5, Direction::Up).unwrap();
        assert_eq!(
            m.h_offset,
            Some(Offset {
                address: 5,
                dir: Direction::Up
            })
        );
        m.cancel_height_offset();
        assert_eq!(m.h_offset, None);
    }
}
