//! # Machine
//!
//! This module represents a **3-Axis Computer Numerical Control** (CNC) machine.
//!
//! The machine runs on parsed [`Code`],
//! generated by the **G-Code [`Parser`](crate::parser::parser)** module.

use crate::parser::{Float, Int, parser::*};
use std::fmt::{Debug, Display};

/// Starting point of a machine with all axes at '0'.
pub const HOME_POS: Point = Point::new(0.0, 0.0, 0.0);

/// Maximum and Minimum values supported for [`Machine::max_travels`] for this module.
/// The fields of these [`Point`]s will be treated in [`Unit::default`] system.
const MAX_TRAVELS: Point = Point::new(1500.0, 1000.0, 1000.0);
const MIN_TRAVELS: Point = Point::new(150.0, 100.0, 100.0);

/// Ratio to maintain between axes lengths.
/// The order of specific axes is as follows:
/// - X : Y
/// - X : Z
/// - Y : Z
const MAX_RATIO: Point = Point::new(2.0, 2.0, 1.5);
const MIN_RATIO: Point = Point::new(1.0, 1.0, 0.5);

/// Possible unit standards for measurable values.
#[derive(Default, Debug)]
pub enum Unit {
    Imperial,
    #[default]
    Metric,
}

/// Possible planes for a 3-axis machine.
#[derive(Default, Debug)]
pub enum Plane {
    #[default]
    XY,
    XZ,
    YZ,
}

/// Possible ways to interpret axis commands.
#[derive(Default, Debug)]
pub enum Positioning {
    #[default]
    Absolute,
    Incremental,
}

/// Possible ways to turn spindle on.
#[derive(Default, Debug)]
pub enum CircularDirection {
    #[default]
    Clockwise,
    CounterClockwise,
}

/// Represents the current state of a [`Machine`](crate::machine).
#[derive(Debug)]
pub struct Machine {
    /// Interpret state values in the selected `units`.
    /// The Code the machine executes MAY OR MAY NOT be in the same units.
    units: Unit,

    /// Interpret [`Code`]s in the selected `code_units`.
    code_units: Unit,

    /// **Positive extreme values** for each linear axis.
    /// The other extreme would naturally be `HOME_POS`.
    /// The values in this struct will be assumed to be in [`units`](Self::units).
    max_travels: Point,

    /// Workpiece offset, used to change relative zero point with `G54`.
    work_offset: Point,

    /// Current position of each axis.
    pos: Point,

    /// Current tool in the spindle.
    tool: Int,

    /// Optionally preload next tool, to be changed on *tool change (`M6`)* command.
    next_tool: Option<Int>,

    /// Commanded RPM for the spindle.
    speed: Option<Int>,
    spindle_on: bool,
    spindle_dir: CircularDirection,

    /// Commanded cutting feed rate.
    feed: Option<Float>,

    coolant: bool,

    /// Plane to execute the [`Code`] on.
    plane: Plane,

    /// Interpret axis values absolutly or relatively.
    positioning: Positioning,

    /// Selected offset for tool diameter with a `D` code.
    dia_offset: Option<Int>,

    /// Selected offset for tool height with a `H` code.
    height_offset: Option<Int>,
}

impl Machine {
    /// Constructs a new instance of [`Machine`] using the [`Unit::default`] measuring system and
    /// all axes at [`HOME_POS`].
    ///
    /// Accepts a [`Point`] indicating positive extremes of the Machine to construct.
    ///
    /// Returns a new `Machine` instance on success or [`MachineError`] on failure.
    ///
    /// # Errors:
    /// - [`MachineError::NegativeTravels`] --
    /// At least one axis is detected to have a negative value.
    /// - [`MachineError::TravelsTooLong`] --
    /// At least one axis is longer than what the constructor supports.
    /// - [`MachineError::TravelsTooShort`] --
    /// At least one axis is shorter than what the constructor supports.
    /// - [`MachineError::WrongRatio`] --
    /// At least two axes have weird values.
    pub fn build(max_travels: Point) -> Result<Self, MachineError> {
        let ratio = max_travels.ratio();

        if max_travels.any_negative() {
            Err(MachineError::NegativeTravels)
        } else if max_travels.over(&MAX_TRAVELS) {
            Err(MachineError::TravelsTooLong)
        } else if max_travels.under(&MIN_TRAVELS) {
            Err(MachineError::TravelsTooShort)
        } else if ratio.over(&MAX_RATIO) || ratio.under(&MIN_RATIO) {
            Err(MachineError::WrongRatio)
        } else {
            Ok(Machine {
                units: Unit::default(),
                code_units: Unit::default(),
                max_travels,
                work_offset: Point::default(),
                pos: Point::default(),
                tool: 0,
                next_tool: None,
                speed: None,
                spindle_on: false,
                spindle_dir: CircularDirection::default(),
                feed: None,
                coolant: false,
                plane: Plane::default(),
                positioning: Positioning::default(),
                dia_offset: None,
                height_offset: None,
            })
        }
    }

    /// Returns the standard [`Unit`] in which [`Code`] values will be interpreted.
    pub fn code_units(&self) -> &Unit {
        &self.code_units
    }

    /// Interpret [`Code`] values in a new [`Unit`] standard.
    pub fn set_code_units(&mut self, code_units: Unit) {
        self.code_units = code_units;
    }

    /// Returns `G54` work coordinate system.
    pub fn work_offset(&self) -> &Point {
        &self.work_offset
    }

    /// Set `G54` work coordinate system.
    ///
    /// **This is not verified to be inside the machine travels**.
    pub fn set_work_offset(&mut self, work_offset: Point) {
        self.work_offset = work_offset;
    }

    /// Returns the current position of the machine.
    pub fn pos(&self) -> &Point {
        &self.pos
    }

    /// Set the current absolute machine position for all axes.
    /// Returns [`MachineError::Overtravel`] if any axis exceeds `max_travels` or `HOME_POS`,
    /// indicating failure.
    pub fn set_pos(&mut self, pos: Point) -> Result<(), MachineError> {
        if pos.over(&self.max_travels) || pos.under(&HOME_POS) {
            Err(MachineError::Overtravel)
        } else {
            self.pos = pos;
            Ok(())
        }
    }

    /// Same as [`Machine::set_pos`], but accepts a [`PartialPoint`] if not all the axes need to
    /// move.
    pub fn set_pos_partial(&mut self, new_pos: PartialPoint) -> Result<(), MachineError> {
        self.set_pos(Point::new(
            new_pos.x().unwrap_or(self.pos.x()),
            new_pos.y().unwrap_or(self.pos.y()),
            new_pos.z().unwrap_or(self.pos.z()),
        ))
    }

    /// Returns a [`Point`] indicating the new position, after moving by `mv`.
    /// Accepts a [`PartialPoint`] `mv` and does not change the fields corresponding to `None`.
    ///
    /// **This is not verified to be inside the machine travels**.
    pub fn new_pos(&self, mv: &PartialPoint) -> Point {
        Point::new(
            self.pos.x() + mv.x().unwrap_or(0.0),
            self.pos.y() + mv.y().unwrap_or(0.0),
            self.pos.z() + mv.z().unwrap_or(0.0),
        )
    }

    /// Set *feedrate* to use.
    pub fn set_feed(&mut self, feed: Float) {
        self.feed = Some(feed);
    }

    /// Set *spindle RPMs* to use.
    pub fn set_speed(&mut self, speed: Int) {
        self.speed = Some(speed);
    }

    /// Turn spindle off.
    pub fn spindle_off(&mut self) {
        self.spindle_on = false;
    }

    /// Prelaod *next tool* to use.
    pub fn set_next_tool(&mut self, next_tool: Int) {
        self.next_tool = Some(next_tool);
    }

    /// Turn spindle on clockwise, if not already on.
    /// Optionally accepts new *spindle speed*, otherwise uses speed for previous block if present.
    ///
    /// Returns [`MachineError::NoSpindleSpeed`] if no spindle speed was commanded before and
    /// `speed` provided is also `None`.
    pub fn spindle_on_cw(&mut self, speed: Option<Int>) -> Result<(), MachineError> {
        self.speed = speed.or(self.speed);
        self.spindle_dir = CircularDirection::Clockwise;

        match self.speed {
            Some(_) => {
                self.spindle_on = true;
                Ok(())
            }
            None => Err(MachineError::NoSpindleSpeed),
        }
    }

    /// Turn spindle on anti-clockwise, if not already on.
    /// Optionally accepts new *spindle speed*, otherwise uses speed for previous block if present.
    ///
    /// Returns [`MachineError::NoSpindleSpeed`] if no spindle speed was commanded before and
    /// `speed` provided is also `None`.
    pub fn spindle_on_ccw(&mut self, speed: Option<Int>) -> Result<(), MachineError> {
        self.speed = speed.or(self.speed);
        self.spindle_dir = CircularDirection::CounterClockwise;

        match self.speed {
            Some(_) => {
                self.spindle_on = true;
                Ok(())
            }
            None => Err(MachineError::NoSpindleSpeed),
        }
    }

    /// Changes current `tool` to:
    /// - `new_tool`, if the value is `Some`.
    /// - `next_tool`, if a tool was preloaded.
    ///
    /// `next_tool` will be always be set to `None` after the tool change.
    ///
    /// Returns [`MachineError::NoTool`] if no `next_tool` was commanded before and
    /// `new_tool` provided is also `None`.
    pub fn tool_change(&mut self, new_tool: Option<Int>) -> Result<(), MachineError> {
        self.next_tool = new_tool.or(self.next_tool);

        match self.next_tool {
            Some(t) => {
                self.tool = t;
                self.next_tool = None;
                Ok(())
            }
            None => Err(MachineError::NoTool),
        }
    }

    /// Set `coolant` on or off.
    pub fn set_coolant(&mut self, coolant: bool) {
        self.coolant = coolant;
    }

    /// Set active plane.
    pub fn set_plane(&mut self, plane: Plane) {
        self.plane = plane;
    }

    /// Toggle between absolute or relative positioning.
    pub fn set_positioning(&mut self, positioning: Positioning) {
        self.positioning = positioning;
    }

    // have 3 methods:
    // set machine pos, if g54 is 0 and absolute mode is set
    // set absolute pos after applying the offset if g54 if present and in absolute mode
    // move machine relatively from current pos if incremental mode is set, regardless if g54 was
    // commanded or not
    //
    // or
    // move absolutely, automatically deals with g54
    // move incrementally by delta
    //
    // set machine pos, for special cases
}

/// Possible errors that can happen during machine construction.
#[derive(Debug, PartialEq)]
pub enum MachineError {
    /// Negative value(s) detected during machine construction.
    NegativeTravels,
    TravelsTooLong,
    TravelsTooShort,
    /// The resulting machine would be an odd shape.
    WrongRatio,
    Overtravel,
    /// Spindle On was commanded, but no spindle speed was provided.
    NoSpindleSpeed,
    /// Tool change was commanded, but no tool number was provided.
    NoTool,
}

impl Display for MachineError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        write!(
            f,
            "{}",
            match self {
                Self::NegativeTravels => format!(
                    "Machine travels cannot be negative.\nPlease provide a valid positive value between: {MAX_TRAVELS:?} and {MIN_TRAVELS:?}"
                ),
                Self::TravelsTooLong => format!(
                    "Cannot construct a 'Machine' this long.\nPlease provide values less than: {MAX_TRAVELS:?}"
                ),
                Self::TravelsTooShort => format!(
                    "Cannot construct a 'Machine' this short.\nPlease provide values larger than: {MIN_TRAVELS:?}"
                ),
                Self::WrongRatio => format!(
                    "The resultant machine would have a particular axis too long or too short.\nPlease reconsider axis lengths."
                ),
                Self::Overtravel => format!(
                    "Overtravel:\nAt least one axis of the machine overtravels because of the last move."
                ),
                Self::NoSpindleSpeed => format!(
                    "No Spindle Speed Commanded:\nA spindle action was commanded, but no 'S' was detected throughout the program."
                ),
                Self::NoTool => format!(
                    "No Tool Commanded:\nA tool change was commanded, but no 'T' was detected on the same block and no tool was preloaded."
                ),
            }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn construct_neg_travels() {
        assert_eq!(
            Machine::build(Point::new(150.0, -500.0, 500.0)).unwrap_err(),
            MachineError::NegativeTravels
        );
    }

    #[test]
    fn construct_long_travels() {
        assert_eq!(
            Machine::build(Point::new(2000.0, 1000.0, 500.0)).unwrap_err(),
            MachineError::TravelsTooLong
        );
    }

    #[test]
    fn construct_short_travels() {
        assert_eq!(
            Machine::build(Point::new(100.0, 75.0, 75.0)).unwrap_err(),
            MachineError::TravelsTooShort
        );
    }

    #[test]
    fn construct_wrong_ratio() {
        assert_eq!(
            Machine::build(Point::new(1500.0, 100.0, 100.0)).unwrap_err(),
            MachineError::WrongRatio
        );
    }

    #[test]
    // Must pass
    fn construct_good() {
        assert!(Machine::build(Point::new(1000.0, 750.0, 500.0)).is_ok());
    }

    // Test Machine methods

    #[test]
    fn overtravel_set() {
        let mut m = Machine::build(Point::new(1000.0, 750.0, 500.0)).unwrap();

        assert_eq!(
            m.set_pos(Point::new(-100.0, 500.0, 300.0)).unwrap_err(),
            MachineError::Overtravel
        );

        assert_eq!(
            m.set_pos(Point::new(1200.0, 500.0, 300.0)).unwrap_err(),
            MachineError::Overtravel
        );
    }
}
