//! # Machine
//!
//! This module represents a **3-Axis Computer Numerical Control** (CNC) machine.
//!
//! The machine runs on parsed [`Code`],
//! generated by the **G-Code [`Parser`](crate::parser::parser)** module.

use crate::parser::{Float, Int, parser::*};
use std::fmt::Debug;

/// Maximum and Minimum values supported for [`Machine::max_travels`] for this module.
/// These values will be treated in [`Unit::default`] system.
const MAX_TRAVELS: (Float, Float, Float) = (1500.0, 1000.0, 1000.0);
const MIN_TRAVELS: (Float, Float, Float) = (150.0, 100.0, 100.0);
/// Ratio to maintain between axes lengths.
const MAX_RATIO: (Float, Float, Float) = (
    (MAX_TRAVELS.0 / MAX_TRAVELS.1) + 1.0,
    (MAX_TRAVELS.0 / MAX_TRAVELS.2) + 1.0,
    (MAX_TRAVELS.1 / MAX_TRAVELS.2) + 1.0,
);
const MIN_RATIO: (Float, Float, Float) = (
    (MAX_TRAVELS.0 / MAX_TRAVELS.1) - 0.5,
    (MAX_TRAVELS.0 / MAX_TRAVELS.2) - 0.5,
    (MAX_TRAVELS.1 / MAX_TRAVELS.2) - 0.5,
);

/// Possible unit standards for measurable values.
#[derive(Default, Debug)]
enum Unit {
    Imperial,
    #[default]
    Metric,
}

/// Possible planes for a 3-axis machine.
#[derive(Default, Debug)]
enum Plane {
    #[default]
    XY,
    XZ,
    YZ,
}

/// Possible ways to interpret axis commands.
#[derive(Default, Debug)]
enum Positioning {
    #[default]
    Absolute,
    Incremental,
}

/// Represents the current state of a [`Machine`](crate::machine).
#[derive(Debug)]
pub struct Machine {
    /// Interpret state values in the selected `units`.
    /// The Code the machine executes MAY OR MAY NOT be in the same units.
    units: Unit,

    /// Interpret [`Code`]s in the selected `code_units`.
    code_units: Unit,

    /// **Positive extreme values** for each linear axis.
    /// The other extreme would naturally be **Zero**.
    /// The values in this struct will be assumed to be in [`units`](Self::units).
    max_travels: Point,

    /// Workpiece offset, used to change relative zero point with `G54`.
    work_offset: Point,

    /// Current position of each axis.
    pos: Point,

    /// Current tool in the spindle.
    tool: Int,

    /// Optionally preload next tool, to be changed on *tool change (`M6`)* command.
    next_tool: Option<Int>,

    /// Commanded RPM for the spindle.
    speed: Option<Int>,
    spindle_on: bool,

    /// Commanded cutting feed rate.
    feed: Option<Float>,

    coolant: bool,

    /// Plane to execute the [`Code`] on.
    plane: Plane,

    /// Interpret axis values absolutly or relatively.
    positioning: Positioning,

    /// Selected offset for tool diameter with a `D` code.
    dia_offset: Option<Int>,

    /// Selected offset for tool height with a `H` code.
    height_offset: Option<Int>,
}

impl Machine {
    /// Constructs a new instance of [`Machine`] using the [`Unit::default`] measuring system.
    ///
    /// Accepts a [`Point`] indicating positive extremes of the Machine to construct.
    ///
    /// Returns a new `Machine` instance on success or [`MachineError`] on failure.
    ///
    /// # Errors:
    /// - [`MachineError::NegativeTravels`] --
    /// At least one axis is detected to have a negative value.
    /// - [`MachineError::TravelsTooLong`] --
    /// At least one axis is longer than what the constructor supports.
    /// - [`MachineError::TravelsTooShort`] --
    /// At least one axis is shorter than what the constructor supports.
    pub fn build(max_travels: Point) -> Result<Self, MachineError> {
        let ratio = max_travels.ratio();

        if max_travels.get() < (0.0, 0.0, 0.0) {
            Err(MachineError::NegativeTravels)
        } else if max_travels.get() > MAX_TRAVELS {
            Err(MachineError::TravelsTooLong)
        } else if max_travels.get() < MIN_TRAVELS {
            Err(MachineError::TravelsTooShort)
        } else if ratio > MAX_RATIO || ratio < MIN_RATIO {
            Err(MachineError::WrongRatio)
        } else {
            Ok(Machine {
                units: Unit::default(),
                code_units: Unit::default(),
                max_travels,
                work_offset: Point::default(),
                pos: Point::default(),
                tool: 0,
                next_tool: None,
                speed: None,
                spindle_on: false,
                feed: None,
                coolant: false,
                plane: Plane::default(),
                positioning: Positioning::default(),
                dia_offset: None,
                height_offset: None,
            })
        }
    }
}

/// Possible errors that can happen during machine construction.
#[derive(PartialEq)]
pub enum MachineError {
    /// Negative value(s) detected during machine construction
    NegativeTravels,
    TravelsTooLong,
    TravelsTooShort,
    /// The resulting machine would be an odd shape
    WrongRatio,
}

impl Debug for MachineError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        write!(
            f,
            "{}",
            match self {
                Self::NegativeTravels => format!(
                    "Machine travels cannot be negative.\nPlease provide a valid positive value between: {MAX_TRAVELS:?} and {MIN_TRAVELS:?}"
                ),
                Self::TravelsTooLong => format!(
                    "Cannot construct a 'Machine' this long.\nPlease provide values less than: {MAX_TRAVELS:?}"
                ),
                Self::TravelsTooShort => format!(
                    "Cannot construct a 'Machine' this short.\nPlease provide values larger than: {MIN_TRAVELS:?}"
                ),
                Self::WrongRatio => format!(
                    "The resultant machine would have a particular axis too long or too short.\nPlease reconsider axis lengths."
                ),
            }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn construct_neg_travels() {
        assert_eq!(
            Machine::build(Point::new(-100.0, 500.0, 500.0)).unwrap_err(),
            MachineError::NegativeTravels
        );
    }

    #[test]
    fn construct_long_travels() {
        assert_eq!(
            Machine::build(Point::new(2000.0, 1000.0, 500.0)).unwrap_err(),
            MachineError::TravelsTooLong
        );
    }

    #[test]
    fn construct_short_travels() {
        assert_eq!(
            Machine::build(Point::new(100.0, 1000.0, 1000.0)).unwrap_err(),
            MachineError::TravelsTooShort
        );
    }

    #[test]
    fn construct_wrong_ratio() {
        assert_eq!(
            Machine::build(Point::new(1500.0, 100.0, 100.0)).unwrap_err(),
            MachineError::WrongRatio
        );
    }
}
