//! # Parser
//!
//! The Parser depends on the output of the Lexer, and is responsible for converting a sequence of
//! tokens to a sequence of [`GCode`]s or [`MCode`]s or a combination of both.
//!
//! Reference used: [Tomassetti](https://tomassetti.me/guide-parsing-algorithms-terminology/)

#![allow(unused)]

use super::lexer::{self, *};
use std::{cmp::PartialEq, fmt::Debug};

/// A *tuple struct* that represents a **3D Point** in space.
///
/// The fields represent X, Y, and Z axis respectively.
///
/// # Example
/// - Storing **max travels** for each axis of a machine where every axis **must** have a value.
/// ```
/// # use gsim_rs::parser::parser::*;
/// let max_travels = Point(40.0, 20.0, 20.0);
/// ```
#[derive(Default, Debug, PartialEq)]
pub struct Point(pub f64, pub f64, pub f64);

/// Same as [`Point`] but the fields can be `None`.
///
/// # Example
/// - Representing a block when [`GCode`] may or may not contain coordinates for each axis.
/// ```
/// # use gsim_rs::parser::parser::*;
/// PartialPoint(
///     Some(1.0),
///     Some(-5.0),
///     None,
/// ); // Represents block: X2. Y-5.
/// ```
#[derive(Default, Debug, PartialEq)]
pub struct PartialPoint(pub Option<f64>, pub Option<f64>, pub Option<f64>);

/// Represents a *complete independent code*, that is,
/// each variant will contain itself and any other code it is required to have.
///
/// Since a [`Code`] variant may be a result of parsing **one or more [`Token`]s**,
/// it may or may not represent an entire *line/block* of code.
///
/// Therefore, it is not necessary that a *line/block* of code be parsed into just one [`Code`]
/// or only one variant of it (*a mix of the variants is also valid in a line/block*).
#[derive(Debug, PartialEq)]
pub enum Code {
    G(GCode),
    M(MCode),
    /// Preload a tool
    Tool(u8),
}

impl Code {
    /// Provides a numeric value of a [`GCode`] or [`MCode`]
    /// by returning a primitive discriminant of the said enumeration.
    ///
    /// The returned number would be the same one that was [`tokenize`]d
    /// by the [`lexer`] as the [`Suffix`].
    ///
    /// # SAFETY
    /// *Not to be used for any other [`Code`] variants.*
    ///
    /// It is certain that the [`GCode`] & [`MCode`] enums specify a primitive representation,
    /// therefore the discriminant may be accessed via *unsafe pointer casting*.
    ///
    /// # PANICS
    ///
    /// The function panics if called on any other variant.
    pub fn suffix(&self) -> u8 {
        match self {
            Self::G(gcode) => unsafe { *(gcode as *const GCode as *const u8) },
            Self::M(mcode) => unsafe { *(mcode as *const MCode as *const u8) },
            _ => panic!("suffix() must only be called on variants: G & M"),
        }
    }
}

/// Represents a *G-code*.
///
/// A G-code is used in toolpaths to move axes of a machine.
///
/// Each variant contains all the other variable values it needs to be a valid.
#[derive(Debug, PartialEq)]
#[repr(u8)]
pub enum GCode {
    /// G00
    /// Linear Interpolate to new coordinates using rapid rate.
    RapidMove(PartialPoint) = 0,
}

impl GCode {
    /// Returns what *group* a [`GCode`] belongs to.
    ///
    /// G-codes can be modal and are divided into *groups*.
    ///
    /// At any given time **only one G-code** from each group can be supplied and be activated.
    /// A line/block of code with more than one G-codes of the same group is **invalid**.
    ///
    /// Reference:
    /// [Haas](https://www.haascnc.com/service/service-content/guide-procedures/what-are-g-codes.html#gsc.tab=0)
    pub fn group(&self) -> u8 {
        match self {
            Self::RapidMove(_) => 01,
        }
    }
}

/// Represents a *M-code*.
///
/// A M-code is used to control machine specific features, mostly as an on-off switch.
///
/// Each variant contains all the other variable values it needs to be a valid.
#[derive(Debug, PartialEq)]
#[repr(u8)]
pub enum MCode {
    /// M00
    /// Program stop.
    Stop = 0,
}

/// Possible errors that can happen during parsing.
#[derive(PartialEq, Debug)]
pub enum ParserError {
    /// Multiple M-codes on the same line.
    MultipleMCodes,
    /// Same G-code found atleast twice.
    DuplicateGCode,
    /// G-codes detected from the same group.
    SameGroupGCode,
}

/// Parses a sequence of *tokens*.
///
/// Accepts a vector of [`Token`]s, which can be empty.
///
/// Returns a vector made up of [`Code`]s on success or [`ParserError`] on failure.
/// The returned vector *may be empty*, only if the passed argument is also an empty vector.
///
/// # Errors
/// - Errors generated by [`validate_block`] are returned *as is*.
///
pub fn parse(mut tokens: Vec<Token>) -> Result<Vec<Code>, ParserError> {
    let mut codes = Vec::new();

    if tokens.is_empty() {
        return Ok(codes);
    }

    validate_block(&tokens)?;

    Ok(codes)
}

/// This function is responsible for performing all the validation on a list of [`Token`]s that are
/// required for it to be parsed correctly.
///
/// The purpose of this validation is to make sure that all the tokens present in the sequence
/// (*a line/block of code*), go well together & do not interfere with one another's functionality.
///
/// The [`parse`] function should not contain any validation of the block.
/// Check [*Errors*](#Errors) section below to see what validations are done by this function.
///
/// # Errors
/// - [`ParserError::MultipleMCodes`] -- Two or more [`MCode`]s found.
pub fn validate_block(tokens: &Vec<Token>) -> Result<(), ParserError> {
    let mut m_found = false;
    let mut g_found = Vec::new();
    let mut g_groups = Vec::new();

    for token in tokens {
        if token.prefix == b'G' {
            // validate gcodes next
            unimplemented!();
        } else if token.prefix == b'M' {
            if m_found {
                return Err(ParserError::MultipleMCodes);
            }
            m_found = true;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{super::lexer::tokenize, *};

    #[test]
    // Test to get the suffix of a code by accessing its discriminant.
    fn get_code_suffix() {
        assert_eq!(
            Code::G(GCode::RapidMove(PartialPoint(None, None, None))).suffix(),
            0
        );
        assert_eq!(Code::M(MCode::Stop).suffix(), 0);
    }

    #[test]
    #[should_panic(expected = "G & M")]
    // Test to get the suffix of an invalid variant.
    fn get_code_suffix_invalid() {
        let _ = Code::Tool(0).suffix();
    }

    #[test]
    // Multiple M codes must be rejected.
    fn multiple_mcodes() {
        assert_eq!(
            parse(tokenize("G40 M5 M9").unwrap()).unwrap_err(),
            ParserError::MultipleMCodes
        );
    }

    // #[test]
    // // Test empty block.
    // fn parse_emtpy() {
    //     assert_eq!(parse(tokenize("").unwrap()).unwrap(), vec![GCode::Empty]);
    // }
    //
    // #[test]
    // // Test rapid move.
    // fn parse_rapid() {
    //     assert_eq!(
    //         parse(tokenize("G00 X0.0 Y0.0").unwrap()).unwrap(),
    //         Vec::<GCode>::new()
    //     );
    // }
}
